# Generated by Django 4.1 on 2023-12-15 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_remove_userinfo_id_alter_userinfo_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userinfo",
            table="userinfo",
        ),
    ]
