# Generated by Django 4.1 on 2023-12-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_champion_city_coach_contract_country_game_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                db_column="team",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.team",
            ),
        ),
    ]
