# Generated by Django 4.1 on 2023-12-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_alter_champion_fmvp_alter_champion_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="player",
            field=models.OneToOneField(
                db_column="country",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app01.player",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.ForeignKey(
                db_column="country",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.country",
            ),
        ),
    ]
