# Generated by Django 4.1 on 2023-12-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_alter_draft_player_alter_player_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="player",
            field=models.OneToOneField(
                db_column="player",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app01.player",
            ),
        ),
    ]
