# Generated by Django 4.1 on 2023-12-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_alter_draft_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="team",
            field=models.OneToOneField(
                db_column="team",
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.team",
            ),
        ),
    ]
