# Generated by Django 4.1 on 2023-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0009_alter_owner_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coach",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="national_league",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
